# YAML configuration file for Docker Compose version 3.8
version: '3.8'

# Define services
services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
    ports:
      - "5432:5432"  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    image: dawnfire05/happit-be
    build: .  # Build the Docker image using the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    depends_on:
      - database
    env_file:
      - .env  # Load environment variables from the .env file in the current directory
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist

volumes:
  postgres_data:
    driver: local
