export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  FORBIDDEN_HABIT_ACCESS: 'FORBIDDEN_HABIT_ACCESS',
  FORBIDDEN_HABIT_UPDATE: 'FORBIDDEN_HABIT_UPDATE',
  FORBIDDEN_HABIT_DELETE: 'FORBIDDEN_HABIT_DELETE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
} as const;
