name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_VARS }}" > .env

    - name: Build the Docker image
      run: docker build -t happit-be .
    - name: taging
      run: docker tag happit-be:latest dawnfire05/happit-be:latest
    - name: Push to Dockerhub
      run: docker push dawnfire05/happit-be:latest