name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Pull Docker image
      run: sudo docker pull dawnfire05/happit-be:latest
    - name: Delete Old docker container
      run: sudo docker rm -f happit-be-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name happit-be-container dawnfire05/happit-be-api